package ua.com.programmer.agentventa.presentation.features.settings

data class UserOptions(
    val isEmpty: Boolean,
    val userId: String = "",
    val allowPriceTypeChoose: Boolean = false,
    val allowReturn: Boolean = false,
    val requireDeliveryDate: Boolean = false,
    val locations: Boolean = false,
    val lastLocationTime: Long = 0,
    val sendPushToken: Boolean = false,
    val loadImages: Boolean = false,
    val watchList: String = "",
    val checkOrderLocation: Boolean = false,
    val read: Boolean = false,
    val token: String = "",
    val write: Boolean = false,
    val license: String = "",
    val editLocations: Boolean = false,
    val currency: String = "",
    val printingEnabled: Boolean = false,
    val showClientPriceOnly: Boolean = false,
    val setClientPrice: Boolean = false,
    val differentialUpdates: Boolean = false,
    val clientsLocations: Boolean = false,
    val clientsDirections: Boolean = false,
    val clientsProducts: Boolean = false,
    val defaultClient: String = "",
    val useDemands: Boolean = false,
    val useCompanies: Boolean = false,
    val useStores: Boolean = false,
    val usePackageMark: Boolean = false,
    val fiscalNumber: String = "",
    val fiscalCashier: String = "",
    val fiscalDeviceId: String = "",
    val fiscalProvider: String = "",
)
